### ISSUE TITLE
Error while loading presets from space graph

### ISSUE THREAD

**Issue by jesse-lane-ai** [acids-ircam/flow_synthesizer#5]
I get this error in terminal from the server (manually started).  A new error is generated every time i click on a preset in latent space.  

```
Exception happened during processing of request from ('127.0.0.1', 53188)
Traceback (most recent call last):
  File "//anaconda3/lib/python3.7/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "//anaconda3/lib/python3.7/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "//anaconda3/lib/python3.7/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "//anaconda3/lib/python3.7/socketserver.py", line 720, in __init__
    self.handle()
  File "//anaconda3/lib/python3.7/site-packages/pythonosc/osc_server.py", line 29, in handle
    self.server.dispatcher.call_handlers_for_packet(self.request[0], self.client_address)
  File "//anaconda3/lib/python3.7/site-packages/pythonosc/dispatcher.py", line 194, in call_handlers_for_packet
    handler.invoke(client_address, timed_msg.message)
  File "//anaconda3/lib/python3.7/site-packages/pythonosc/dispatcher.py", line 57, in invoke
    self.callback(message.address, *message)
  File "/Users/username/projects/flow_synthesizer-master/code/osc_server.py", line 95, in func_embedding
    return func(*t_args, **kwargs)
  File "/Users/username/projects/flow_synthesizer-master/code/osc_server.py", line 502, in load_preset
    loaded = np.load(cur_file, allow_pickle=True)
  File "//anaconda3/lib/python3.7/site-packages/numpy/lib/npyio.py", line 422, in load
    fid = open(os_fspath(file), "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/Users/username/Datasets/diva_dataset/64par/raw/b6ef2f0bb6101f7c5ed2edc97519f024_60_100.npz'
```

**Comment by esling** [comment]
Hey @RokaMic, 

Sorry, the README is not super clear on that part (I'll update it afterwards), but the preset themselves are actually part of the dataset used for training and testing that can be downloaded here :
https://github.com/acids-ircam/flow_synthesizer#dataset 

You can then put it in a /Users/<your_name>/Datasets/ folder and it should work :)

**Comment by jesse-lane-ai** [comment]
Thank you for the clarification.  I suspected I was missing some files.
